name = "sqlresume"
compatibility_date = "2024-01-17"
node_compat = true

[build]
command = "npm run build"

pages_build_output_dir = ".vercel/output/static"

[[build.upload]]
type = "directory"
dir = ".vercel/output/static"